name: 'kubectl in EKS'
author: Jarvan1
description: An action allowing you to integrate with EKS via kubectl in a Github Action, easily...
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jarvan1/eks-kubectl-action:latest'
inputs:
  aws_access_key_id:
    description: Your AWS_ACCESS_KEY_ID
    required: false
  aws_secret_access_key:
    description: Your AWS_SECRET_ACCESS_KEY
    required: false
  aws_region:
    description: The region of the cluster
    required: false
  cluster_name:
    description: The name of the cluster you're using
    required: true
  eks_role_arn:
    description: EKS role arn that allow access eks cluster (Mostly happen when you create your cluster with CDK).
    required: false
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
  manifests_file:
    description: The mainfests file to deploy to K8S
    required: false
  image:
    description: The image in manifests file
    required: false
outputs:
  kubectl-out:
    description: The output of the kubectl command
